### ISSUE TITLE
Attempting to add navigator-badge to backpack results in "We have encountered the following problem: user is not logged in, redirect to /backpack/login"

### ISSUE THREAD

**Issue by edmorley** [toolness/hackasaurus-parable#1]
1) Visit http://toolness.github.io/hackasaurus-parable/navigator-badge/
2) Complete tasks
3) Enter email & click "send to backpack"
4) On popup, click "log in or sign up"
5) On Persona popup, click "sign in" next to existing email address.

Expected:
Login succeeds, confirmation of adding 1 badge to backpack shown.

Actual:
The popup at step #4 displays:
"We have encountered the following problem: user is not logged in, redirect to /backpack/login"
...in an error banner. And below that:
"You didn't add any open badges to your backpack."

Mozilla/5.0 (Windows NT 6.2; WOW64; rv:27.0) Gecko/20100101 Firefox/27.0
Nightly built from http://hg.mozilla.org/mozilla-central/rev/c22969eec61d
Didn't work in safe mode either.

**Comment by xmatthewx** [comment]
I was not able to push to backpack either. I completed items, entered email, but waiting image continued to spin. No error was reported.

**Comment by toolness** [comment]
Hey, I think this is fixed now--sorry for the super late response to this... Feel free to re-open this issue if you encounter it again, though!

**Comment by CBoensel** [comment]
Actually the same bug is still there I think: https://dl.dropboxusercontent.com/u/5282959/OpenBadge_error.PNG
windows 8.1, Firefox 29.0 but also older versions
